#!/bin/sh
set -aue

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

USER_BASE_MODEL_API_KEY="${BASE_MODEL_API_KEY-}"
USER_BASE_MODEL_NAME="${BASE_MODEL_NAME-}"
USER_LLAMA_SERVER_BIN="${LLAMA_SERVER_BIN-}"
USER_LOCAL_MODEL_PATH="${LOCAL_MODEL_PATH-}"
USER_LLAMA_SERVER_HOST="${LLAMA_SERVER_HOST-}"
USER_LLAMA_SERVER_PORT="${LLAMA_SERVER_PORT-}"
USER_LLAMA_CTX_SIZE="${LLAMA_CTX_SIZE-}"
USER_LLAMA_PARALLEL="${LLAMA_PARALLEL-}"
USER_LLAMA_THREADS="${LLAMA_THREADS-}"
USER_LLAMA_N_GPU_LAYERS="${LLAMA_N_GPU_LAYERS-}"
USER_LLAMA_BATCH_SIZE="${LLAMA_BATCH_SIZE-}"
USER_LLAMA_UBATCH_SIZE="${LLAMA_UBATCH_SIZE-}"
USER_LLAMA_JINJA="${LLAMA_JINJA-}"

load_env() {
  if [ ! -f "$1" ]; then
    echo "Missing environment file: $1" >&2
    echo "Create it with: cp .env.example .env" >&2
    exit 1
  fi
  ENV_FILE="${TMPDIR:-/tmp}/gaia-pipeline-env.$$"
  tr -d '\r' < "$1" > "${ENV_FILE}"
  . "${ENV_FILE}"
  rm -f "${ENV_FILE}"
}

load_env "${REPO_ROOT}/.env"

# Ubuntu/local entrypoint: use the llama-server already installed on the host.
# Keep benchmark settings in .env; keep model-serving choices here.
BASE_MODEL_RUNNER_TYPE=llamaLocal

BASE_MODEL_API_KEY="${USER_BASE_MODEL_API_KEY:-local}"
BASE_MODEL_NAME="${USER_BASE_MODEL_NAME:-qwen3.5-9b-gguf-q4}"
LLAMA_SERVER_BIN="${USER_LLAMA_SERVER_BIN:-llama-server}"
LOCAL_MODEL_PATH="${USER_LOCAL_MODEL_PATH:-/home/user/models/Qwen3.5-9B-Q4_K_M.gguf}"
LLAMA_SERVER_HOST="${USER_LLAMA_SERVER_HOST:-127.0.0.1}"
LLAMA_SERVER_PORT="${USER_LLAMA_SERVER_PORT:-18082}"
LLAMA_CTX_SIZE="${USER_LLAMA_CTX_SIZE:-32768}"
LLAMA_PARALLEL="${USER_LLAMA_PARALLEL:-1}"
LLAMA_THREADS="${USER_LLAMA_THREADS:-4}"
LLAMA_N_GPU_LAYERS="${USER_LLAMA_N_GPU_LAYERS:-999}"
LLAMA_BATCH_SIZE="${USER_LLAMA_BATCH_SIZE:-512}"
LLAMA_UBATCH_SIZE="${USER_LLAMA_UBATCH_SIZE:-128}"
LLAMA_JINJA="${USER_LLAMA_JINJA:-auto}"

# If a conda env is active, use it instead of creating .venv.
if [ -n "${CONDA_PREFIX:-}" ] && [ -z "${PYTHON_BIN:-}" ] && [ -z "${RUNNER_MANAGED_VENV:-}" ]; then
  RUNNER_MANAGED_VENV=0
fi

export BASE_MODEL_RUNNER_TYPE BASE_MODEL_API_KEY BASE_MODEL_NAME
export LLAMA_SERVER_BIN LOCAL_MODEL_PATH LLAMA_SERVER_HOST LLAMA_SERVER_PORT
export LLAMA_CTX_SIZE LLAMA_PARALLEL LLAMA_THREADS LLAMA_N_GPU_LAYERS
export LLAMA_BATCH_SIZE LLAMA_UBATCH_SIZE LLAMA_JINJA
START_ENV_LOADED=1
export RUNNER_MANAGED_VENV START_ENV_LOADED

exec sh "${REPO_ROOT}/runner/start.sh" "${BASE_MODEL_RUNNER_TYPE}"
